### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [Creeperface01/WorldFixer#1]
Hello @Creeperface01 ,sorry for inutile issue (first issue ,omg) ,please ,you can create one wiki how compile plugin ?

Thanks. I need because i want to edit plugin ( i have permission please? ) for my server ?
I want to change color to : 163,224,83 or 0xA3E053 ,because is more beautiful :)

Thanks and please answer ! :)

**Comment by ghost** [comment]
@Creeperface01

**Comment by Creeperface01** [comment]
You can but ill add custom color support

**Comment by Creeperface01** [comment]
you can create pull requet

**Comment by ghost** [comment]
But,you can create please one wiki's how compile this jar? :) @Creeperface01

**Comment by Creeperface01** [comment]
but this plugin is not done yet
