### ISSUE TITLE
php

### ISSUE THREAD

**Issue by GamakCZ** [Creeperface01/WorldFixer#5]
mohu si vzít php verzi na starost?

**Comment by Creeperface01** [comment]
Si udělej fork ale

**Comment by GamakCZ** [comment]
z javy fork?

**Comment by Creeperface01** [comment]
Však tu není php verze už

**Comment by GamakCZ** [comment]
Já ji mam ;-)

**Comment by GamakCZ** [comment]
https://github.com/CzechPMDevs/WorldFixer

**Comment by Creeperface01** [comment]
Mě to je jedno

**Comment by GamakCZ** [comment]
ok tak já to dam na poggit

**Comment by GamakCZ** [comment]
jestli s tím souhlasíš
