### ISSUE TITLE
1.6 Doesn't work

### ISSUE THREAD

**Issue by Guillaume351** [Creeperface01/WorldFixer#9]
Hello,
I've tried WorldFixer 1.6 with latest Nukkit from master branch (Nukkit 1.0) and a java world from 1.12.
When I do /wf fixlevel world, I receive "null" in game, and nothing happens. When I do "wf fixlevel world" from console, the same thing happens.
The only command that works is /wf help
I don't have any other plugins. I also tried with Nukkit from 1.16 features branch.
Thank you

**Comment by Creeperface01** [comment]
Hi, can you send me the world you're trying to convert? I've tried today and everything worked well so idk 🤔

**Comment by Guillaume351** [comment]
Thank you for your fast answer. Well I can send it privately to you, but even if I try to fix a nukkit generated world, I get no message  but "null". Seems like it's not even trying

**Comment by Guillaume351** [comment]
I may be wrong, but line 50 you are loading world named args[1]. But when I do "/wf fixlevel worldname" the world name is args[2]. What's strange is that it doesn't tell me that the world doesn't exist. It doesn't answer at all

**Comment by Guillaume351** [comment]
Tested on an other computer, latest nukkit, worldfixer 1.6, and for some reasons now it works (only from in game, but that's intended apparently). Thanks
